version: '3'
services:
  web:
    build:
      context: .   #Look into current directory to find the Dockerfile
      dockerfile: Dockerfile.dev     #name of the file to find
    ports:
      - "8000:3000"
    volumes:
      - /app/node_modules
      - .:/app   #current folder of outside the container to app folder of inside the container.

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app 
    command: ["npm", "run", "test"]
